name: Deploy Science Site
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Bunny.net
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.5
        with:
          source: "./"
          storageZoneName: "totally-science"
          storagePassword: ${{ secrets.BUNNY_STORAGE_PASSWORD }}
          upload: "true"
          remove: "true"
